### ISSUE TITLE
nonenumerable props?

### ISSUE THREAD

**Issue by mesqueeb** [planttheidea/fast-copy#26]
this didn't work for me:
```js
  let target, res
  target = { value: 42 }
  Object.defineProperty(target, 'id', {
    value: 1,
    writable: true,
    enumerable: false,
    configurable: true
  })
  res = copy(target)
  t.is(res.id, 1)
```

**Comment by planttheidea** [comment]
By default, no, only enumerable properties are copied. However, this edge case is one of the reasons `copy.strict` was added, it should copy the key with the same object descriptor. It is not as fast, but it should produce the result you seek.
