### ISSUE TITLE
Objects used multiple times in source object are not copied correctly

### ISSUE THREAD

**Issue by darkowic** [planttheidea/fast-copy#27]
If a non-extensible object reference is used multiple times in the copied object, then the non-extensible object is still existing in the copied object. It's difficult to explain that - here is a reproduction case - https://codesandbox.io/s/fast-copy-non-extensible-bug-cv0vh

I checked the source code and looks like it is an issue with the cache. Maybe I will take a look at it.

**Comment by darkowic** [comment]
It is even worse - the whole object is the same

**Comment by planttheidea** [comment]
Thanks for the PR! This should be fixed as-of `2.0.5`.

**Comment by darkowic** [comment]
@planttheidea you forgot to update CHANGELOG ;)

**Comment by planttheidea** [comment]
Ack sorry you're right. I'll make sure to do that tonight.
