### ISSUE TITLE
relative margin of error

### ISSUE THREAD

**Issue by ksnyde** [planttheidea/fast-copy#4]
I like the performance metrics you’re producing but wasn’t clear on what “relative margin of error” meant. I suspect other passers by will have this question so this is in the hope that you can update the README with a simple description of what this is and how it’s measured.

**Comment by planttheidea** [comment]
The values are automatically provided by the `benchmark` library, but it is just a mathematics concept when dealing with the confidence of averages.

https://en.m.wikipedia.org/wiki/Margin_of_error
