### ISSUE TITLE
Add existence checks on realm.Date and realm.RegExp

### ISSUE THREAD

**Issue by tuckertrainor** [planttheidea/fast-copy#48]
Hello! I code in a framework that builds applications for iOS and Android (via [React Native](https://reactnative.dev)) and the web (via [React Native for Web](https://github.com/necolas/react-native-web)). As part of server-side rendering for web, the framework has a small number of basic polyfills for the [Ww]indow object.

Recently when testing server-side network calls through the client function of an npm package that uses fast-copy, I saw the following error:
```
TypeError: Right-hand side of 'instanceof' is not an object
```
I traced this error back to my web application not including a `Date` or `RegExp` object in its polyfills for server-side rendering. As a result, if the [FastCopy Realm is set as the Window object](https://github.com/planttheidea/fast-copy/blob/7dfe0418795fc5b066a1b064932313e4eb804036/src/fast-copy.d.ts#L3), and the Window object does not include `Date` or `RegExp` objects, then the `handleCopy` function throws the TypeError if [checking `instanceof` against `realm.Date` or `realm.Regexp`](https://github.com/planttheidea/fast-copy/blob/7dfe0418795fc5b066a1b064932313e4eb804036/src/index.ts#L95-L107).

Though I was able to add polyfills in my application to supplement those in the framework and solve for my particular use case, can we add existence checks for `realm.Date` and `realm.RegExp` in `handleCopy` similar to that of other `realm` objects? I would be glad to put together a PR if you agree with this suggestion.

**Comment by planttheidea** [comment]
I'm not opposed to this, but I'm curious what JS environment exists that has better `Date` nor `RegExp` as global objects? The reason those have no existence checks is because their presence should be guaranteed.

If you could provide a repro of the issue, it may help me better understand why those objects don't exist.

**Comment by tuckertrainor** [comment]
Thanks for the quick reply. You make an excellent point in whether a JS environment exists without `Date` or `RegExp` objects. For context of how I came across this, I am implementing [contentful](https://www.npmjs.com/package/contentful) data into a web application based on the [flagship](https://www.npmjs.com/package/@brandingbrand/flagship) framework. What I think is happening is that as it builds an ersatz JS environment to render RN/RNW content server-side (without the benefit of `window` or `document` objects as the rendering occurs on an Express JS app), it creates a server-side render config that [includes](https://github.com/brandingbrand/flagship/blob/7f9d8c553df98de6b5b8ea66811795ae9901b202/packages/fsweb/webpack.ssr.js#L68) a [polyfill](https://github.com/brandingbrand/flagship/blob/7f9d8c553df98de6b5b8ea66811795ae9901b202/packages/fsweb/polyfills/window.js) that lacks `Date` or `RegExp` objects.

When making a server-side call to a contentful client in this environment, I am seeing that the Realm object matches the polyfill, so I think my application environment's `window` polyfill is being returned by `GLOBAL_THIS` and thus `realm.Date` and `realm.RegExp` don't exist in `realm` since they didn't exist in the polyfill.

In any case, since my application passes a `window` polyfill that lacks these expected objects and that I cannot reproduce the issue with a vanilla Express application calling a contentful client (and have never reproduced in client-side calls), showing that the issue lies more with the incomplete SSR polyfill, I am fine with closing this issue as a non-issue in light of your reply.
