### ISSUE TITLE
There are serious performance issues When used in many places

### ISSUE THREAD

**Issue by mezhanglei** [planttheidea/fast-copy#58]
When this function is executed multiple times and setState in react, it triggers a noticeable lag of up to a few seconds

**Comment by planttheidea** [comment]
Any chance you can provide a repro?

**Comment by mezhanglei** [comment]
> Any chance you can provide a repro?

I can provide my personal project, after launching the project, the home page, there will be several divs to drag and drop, the more times you drag and drop, the longer the lag time. Search for the keyword 'mergeObject' to find where the code is used。
https://github.com/mezhanglei/zhanglei_react_web

**Comment by planttheidea** [comment]
That is a massive project, with many nuanced Alexis to it that could be contributing to your perceived performance issues. Can you provide a more targeted repro? Something simple and digestible?

**Comment by planttheidea** [comment]
Also, what other deep clone libraries have you tried for comparison?

**Comment by mezhanglei** [comment]
> Also, what other deep clone libraries have you tried for comparison?

I'm pretty sure it's this deep copy library that's causing the problem, the other libraries I've chosen so far are immer, which is fine, but immer is not compatible with ie, do you have a good alternative?

**Comment by mezhanglei** [comment]
> Also, what other deep clone libraries have you tried for comparison?
You can go directly to my project, it's very simple, just download it and start it, you can try to reproduce the problem I mentioned, it uses 'mergeObject' and I'll point it out to you

**Comment by mezhanglei** [comment]
Search for 'mergeObject' in the editor, the first position is where the problem is

**Comment by mezhanglei** [comment]
> Also, what other deep clone libraries have you tried for comparison?

Search for 'mergeObject' in the editor, the first position is where the problem is

**Comment by planttheidea** [comment]
If you are unable to provide a simple repro that doesn't involve debugging your entire project, then I'm afraid I can't help you. If you search for "deep copy" on npm, you may find a more suitable library for your use cases.
