### ISSUE TITLE
CDN version

### ISSUE THREAD

**Issue by 1isten** [planttheidea/fast-copy#75]
How to use this package via CDN?  I've tried https://cdn.jsdelivr.net/npm/fast-copy@3.0.0/dist/umd/index.js but seems no global function exported to the `window` object.

**Comment by planttheidea** [comment]
You are correct that a global _function_ is not exported to the window object, however a _namespace_ is. This was an aspect of the [breaking changes](https://github.com/planttheidea/fast-copy/blob/master/CHANGELOG.md#300) where exports are always named. I mentioned it was for CJS, but the same applies to UMD where you have instantiated a global.

To use the package via CDN, just add the `default` property to the global retrieved:

```js
const copy = globalThis['fast-copy'].default;
```

[Example with a CodePen](https://codepen.io/planttheidea/pen/KKRGEZN)

I'll update the explanation in the CHANGELOG to include this.
