### ISSUE TITLE
fast-copy not compatible with NodeJS's --disable-proto=throw option

### ISSUE THREAD

**Issue by castarco** [planttheidea/fast-copy#79]
When running NodeJS with `--disable-proto` option, fast-copy fails due to an access to the `__proto__` property. Many people need/want to avoid this kind of access because it facilitates "prototype pollution" attacks.

- https://learn.snyk.io/lessons/prototype-pollution/javascript/

**Comment by planttheidea** [comment]
The fix you submitted has been released as part of `3.0.1`. Thank you very much for your contribution! If you have any more issues, please let me know.
